name: Android CI

on: [push, pull_request]

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Build app
        run: |
          cd android/app
          ./gradlew build --stacktrace
